<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\Scrollium.Application\Scrollium.Application.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="LibGit2Sharp" />
    <PackageReference Include="WeCantSpell.Hunspell" />
    <PackageReference Include="DocumentFormat.OpenXml" />
  </ItemGroup>
</Project>
